# Generated by Django 3.2.5 on 2021-08-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20210809_1503'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
