# Generated by Django 3.2.5 on 2021-08-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('last_price', models.FloatField(default=0)),
                ('spread', models.FloatField(default=0.001)),
                ('market', models.CharField(choices=[('FX', 'Forex'), ('ST', 'Stock'), ('CR', 'Cryptocurrency'), ('CF', 'CommodityFutures'), ('IN', 'Index')], default='ST', max_length=2)),
                ('tick_size_of_price', models.IntegerField(default=5)),
                ('minimum_quantity_decimal_point', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('pip', models.IntegerField(default=10000)),
            ],
        ),
    ]
