# Generated by Django 3.2.5 on 2021-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='profile_picture',
            field=models.ImageField(default='symbol_logo/default.png', upload_to='symbol-logo/'),
        ),
    ]
