# Generated by Django 3.2.5 on 2021-08-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='last_price',
            field=models.FloatField(default=0),
        ),
    ]
