# Generated by Django 3.2.5 on 2021-08-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stock_last_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30, unique=True)),
                ('last_price', models.FloatField(default=0)),
            ],
        ),
    ]
