# Generated by Django 3.2.5 on 2021-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_symbol_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30, unique=True)),
                ('sector', models.CharField(choices=[('TG', 'Thematic Growth'), ('IN', 'Income'), ('IA', 'International Access'), ('CM', 'Commodities'), ('OS', 'Other Strategies')], default='TG', max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='symbol',
            old_name='profile_picture',
            new_name='logo',
        ),
    ]
