# Generated by Django 3.2.5 on 2021-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210912_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
