# Generated by Django 3.2.5 on 2021-08-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_symbol_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='market',
            field=models.CharField(choices=[('FX', 'Forex'), ('ST', 'Stock'), ('CR', 'Cryptocurreny'), ('CF', 'CommodityFutures'), ('IN', 'Index')], default='ST', max_length=2),
        ),
    ]
