# Generated by Django 3.2.5 on 2021-08-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cryptocurrencies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrencies',
            old_name='ticker',
            new_name='name',
        ),
    ]
