# Generated by Django 3.2.5 on 2021-08-07 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ticker_cryptocurrencies_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoCurrencies',
            new_name='CryptoCurrency',
        ),
    ]
