# Generated by Django 3.2.5 on 2021-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_symbol_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='minimum_quantity_decimal_point',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='symbol',
            name='pip_value',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='symbol',
            name='tick_size_of_price',
            field=models.IntegerField(default=5),
        ),
    ]
