# Generated by Django 3.2.5 on 2021-09-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_etf_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
