# Generated by Django 3.2.5 on 2021-08-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_cryptocurrencies_cryptocurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=30, unique=True)),
                ('bid', models.FloatField(default=0)),
                ('ask', models.FloatField(default=0)),
            ],
        ),
    ]
