# Generated by Django 3.2.5 on 2021-08-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210815_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='pip_value',
        ),
        migrations.AddField(
            model_name='symbol',
            name='pip',
            field=models.IntegerField(default=1000),
        ),
    ]
