# Generated by Django 3.2.5 on 2021-09-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_etf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='sector',
            field=models.CharField(choices=[('Thematic_Growth', 'Thematic Growth'), ('Income', 'Income'), ('International_Access', 'International Access'), ('Commodities', 'Commodities'), ('Other_Strategies', 'Other Strategies')], default='Thematic_Growth', max_length=25),
        ),
    ]
