# Generated by Django 3.2.5 on 2021-09-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_etf_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etf',
            name='sector',
            field=models.CharField(choices=[('TG', 'Thematic Growth'), ('IN', 'Income'), ('IA', 'International Access'), ('CM', 'Commodities'), ('OS', 'Other Strategies')], default='TG', max_length=2),
        ),
    ]
