# Generated by Django 3.2.5 on 2021-08-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210816_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='pip',
            field=models.IntegerField(default=10000),
        ),
    ]
