# Generated by Django 3.2.5 on 2021-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_futurescontract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('ticker', models.CharField(max_length=30, unique=True)),
                ('last_price', models.FloatField(default=0)),
            ],
        ),
    ]
