# Generated by Django 3.2.5 on 2021-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_symbol_pip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
        migrations.DeleteModel(
            name='ForexPair',
        ),
        migrations.DeleteModel(
            name='FuturesContract',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterField(
            model_name='symbol',
            name='market',
            field=models.CharField(choices=[('FX', 'Forex'), ('ST', 'Stock'), ('CR', 'Cryptocurrency'), ('CF', 'CommodityFutures'), ('IN', 'Index')], default='ST', max_length=2),
        ),
    ]
