# Generated by Django 3.2.5 on 2021-08-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurescontract',
            name='id',
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='ticker_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
