# Generated by Django 3.2.5 on 2021-08-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210818_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
