# Generated by Django 3.2.5 on 2021-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210811_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('ticker', models.CharField(max_length=30, unique=True)),
                ('last_price', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='futurescontract',
            name='ticker_id',
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
