# Generated by Django 3.2.5 on 2021-08-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210811_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexpair',
            name='ticker_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
