# Generated by Django 3.2.5 on 2021-08-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_forexpair_ticker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexpair',
            name='ticker_id',
        ),
        migrations.AddField(
            model_name='futurescontract',
            name='ticker_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
