# Generated by Django 3.2.5 on 2021-08-11 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210811_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futurescontract',
            name='ticker_id',
        ),
    ]
