# Generated by Django 3.2.5 on 2021-08-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leverage',
        ),
    ]
