# Generated by Django 3.2.5 on 2021-08-21 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0003_auto_20210819_1935'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_media', '0002_auto_20210821_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('text_content', models.TextField(null=True)),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('related_trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paper_trade.orderopenposition')),
            ],
        ),
    ]
