# Generated by Django 3.2.5 on 2021-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_margin',
            field=models.FloatField(default=100000),
        ),
    ]
