# Generated by Django 3.2.5 on 2021-08-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0003_auto_20210819_1935'),
        ('social_media', '0003_signalpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalpost',
            name='related_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paper_trade.orderopenposition'),
        ),
    ]
