# Generated by Django 3.2.5 on 2021-08-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0003_profile_free_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_margin',
            field=models.FloatField(default=models.FloatField(default=100000)),
        ),
    ]
