# Generated by Django 3.2.5 on 2021-08-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0004_alter_profile_free_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='leverage',
            field=models.IntegerField(default=200),
        ),
    ]
