# Generated by Django 3.2.5 on 2021-08-21 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
        ('social_media', '0004_alter_signalpost_related_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('text_content', models.TextField(null=True)),
                ('symbol_initial_bid_price', models.FloatField(blank=True, null=True)),
                ('symbol_initial_ask_price', models.FloatField(blank=True, null=True)),
                ('likes', models.ManyToManyField(related_name='likes_relation', to=settings.AUTH_USER_MODEL)),
                ('related_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SignalPost',
        ),
    ]
