# Generated by Django 3.2.5 on 2021-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0005_profile_leverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='free_margin',
            field=models.FloatField(default=100000),
        ),
    ]
