# Generated by Django 3.2.5 on 2021-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0006_userfollow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollow',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('followed_user', 'following_user'), name='unique_followers'),
        ),
    ]
