# Generated by Django 3.2.5 on 2021-08-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0008_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_post_public',
            field=models.BooleanField(default=True),
        ),
    ]
