# Generated by Django 3.2.5 on 2021-08-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0009_profile_is_post_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_signal_public',
            field=models.BooleanField(default=False),
        ),
    ]
