# Generated by Django 3.2.5 on 2021-08-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0010_profile_is_signal_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_post_public',
            field=models.BooleanField(default=True, help_text="Do you want your post to published publicly? It means that all users, even those who havn't followed you will see them"),
        ),
    ]
