# Generated by Django 3.2.5 on 2021-08-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0012_alter_profile_is_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_post_public',
            field=models.BooleanField(default=True, help_text="* What does this mean?  If you choose it, all users, even those who havn't followed you will see your post. If you don't choose it, only your followers will see it"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_signal_public',
            field=models.BooleanField(default=False, help_text="* What does this mean?  If you choose it, all users, even those who havn't followed you will see your post. If you don't choose it, only your followers will see it"),
        ),
    ]
