# Generated by Django 3.2.5 on 2021-08-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0013_auto_20210824_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_post_public',
            field=models.BooleanField(default=True, help_text="* What does this mean?  If it is active, all users, even those who havn't followed you will see your post. If not, only your followers will see them"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_signal_public',
            field=models.BooleanField(default=False, help_text="* What does this mean?  If it is active, all users, even those who havn't followed you will see your signals. If not, only your followers will see them"),
        ),
    ]
