# Generated by Django 3.2.5 on 2021-08-24 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('social_media', '0014_auto_20210824_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.symbol'),
        ),
    ]
