# Generated by Django 3.2.5 on 2021-08-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0015_alter_post_related_symbol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.png', upload_to='profile_pictures/'),
        ),
    ]
