# Generated by Django 3.2.5 on 2021-08-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_matched',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
