# Generated by Django 3.2.5 on 2021-08-11 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210811_1030'),
        ('paper_trade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='futurescontract_ptr',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='ticker_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.ticker'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticker'),
        ),
    ]
