# Generated by Django 3.2.5 on 2021-08-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderopenposition',
            name='current_quantity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderopenposition',
            name='initial_margin',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
