# Generated by Django 3.2.5 on 2021-08-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0002_auto_20210819_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='position',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.DeleteModel(
            name='OpenPositionOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
