# Generated by Django 3.2.5 on 2021-08-13 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_ticker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper_trade', '0002_order_price_matched'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPositionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('price_matched', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('L', 'Long'), ('S', 'Short')], max_length=1)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
