# Generated by Django 3.2.5 on 2021-08-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0003_auto_20210819_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderopenposition',
            name='signal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
