# Generated by Django 3.2.5 on 2021-08-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0003_openpositionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
