# Generated by Django 3.2.5 on 2021-08-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0004_orderopenposition_signal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderopenposition',
            old_name='signal',
            new_name='signal_text',
        ),
    ]
