# Generated by Django 3.2.5 on 2021-08-21 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0005_rename_signal_orderopenposition_signal_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderopenposition',
            name='initial_quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
