# Generated by Django 3.2.5 on 2021-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0005_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='blocked_margin',
            field=models.FloatField(null=True),
        ),
    ]
