# Generated by Django 3.2.5 on 2021-08-18 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_symbol_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paper_trade', '0006_position_blocked_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_price', models.FloatField()),
                ('price_matched', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('direction', models.IntegerField(choices=[(1, 'Long'), (-1, 'Short')])),
                ('result', models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], default='F', max_length=1)),
                ('leverage', models.IntegerField(default=1)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderClosePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_price', models.FloatField()),
                ('close_position_price', models.FloatField(blank=True)),
                ('open_position_price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('direction', models.IntegerField(choices=[(1, 'Long'), (-1, 'Short')])),
                ('result', models.CharField(choices=[('S', 'Success'), ('F', 'Failure')], default='F', max_length=1)),
                ('freed_margin', models.FloatField(blank=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('direction', models.IntegerField(choices=[(1, 'Long'), (-1, 'Short')])),
                ('matched_price', models.FloatField()),
                ('blocked_margin', models.FloatField(null=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('take_profit', models.FloatField(blank=True, null=True)),
                ('stop_loss', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symbol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
