# Generated by Django 3.2.5 on 2021-08-21 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0006_alter_orderopenposition_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderopenposition',
            name='initial_quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06)]),
        ),
    ]
