# Generated by Django 3.2.5 on 2021-08-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0007_openposition_ordercloseposition_orderopenposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercloseposition',
            name='direction',
            field=models.IntegerField(blank=True, choices=[(1, 'Long'), (-1, 'Short')]),
        ),
        migrations.AlterField(
            model_name='ordercloseposition',
            name='open_position_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderopenposition',
            name='leverage',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
