# Generated by Django 3.2.5 on 2021-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0008_auto_20210818_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercloseposition',
            name='close_position_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordercloseposition',
            name='open_position_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
