# Generated by Django 3.2.5 on 2021-08-21 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0008_alter_orderopenposition_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercloseposition',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1e-06, message='Enter a positive number')]),
        ),
    ]
