# Generated by Django 3.2.5 on 2021-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0009_auto_20210818_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercloseposition',
            name='direction',
            field=models.IntegerField(blank=True, choices=[(1, 'Long'), (-1, 'Short')], null=True),
        ),
        migrations.AlterField(
            model_name='ordercloseposition',
            name='freed_margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
