# Generated by Django 3.2.5 on 2021-08-21 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0009_alter_ordercloseposition_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercloseposition',
            name='input_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Enter a positive number')]),
        ),
        migrations.AlterField(
            model_name='orderopenposition',
            name='input_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, message='Enter a positive number')]),
        ),
        migrations.AlterField(
            model_name='orderopenposition',
            name='leverage',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0, message='Enter a positive number')]),
        ),
        migrations.AlterField(
            model_name='orderopenposition',
            name='stop_loss',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Enter a positive number')]),
        ),
        migrations.AlterField(
            model_name='orderopenposition',
            name='take_profit',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Enter a positive number')]),
        ),
    ]
