# Generated by Django 3.2.5 on 2021-08-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0010_auto_20210821_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderopenposition',
            options={'ordering': ['-created_datetime']},
        ),
    ]
