# Generated by Django 3.2.5 on 2021-08-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper_trade', '0010_auto_20210818_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderopenposition',
            old_name='quantity',
            new_name='initial_quantity',
        ),
        migrations.RenameField(
            model_name='orderopenposition',
            old_name='price_matched',
            new_name='matched_price',
        ),
        migrations.AddField(
            model_name='orderopenposition',
            name='current_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderopenposition',
            name='initial_margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
